---
- name: restart alertmanager
  become: true
  service:
    name: alertmanager
    state: restarted

- name: reload alertmanager
  become: true
  systemd:
    name: alertmanager
    state: reloaded
